#define WINDOW_WIDTH 1650
#define WINDOW_HEIGHT 800

#define BRIDGE_WIDTH 500
#define BRIDGE_HEIGHT 8
#define BRIDGE_Y (WINDOW_HEIGHT - BRIDGE_HEIGHT)
#define BRIDGE_X (WINDOW_WIDTH / 2) - (BRIDGE_WIDTH / 2)

#define NUM_OF_ANTI_AIRCRAFTS 2
#define ANTI_AIRCRAFT_WIDTH 125
#define ANTI_AIRCRAFT_HEIGHT 75
#define ANTI_AIRCRAFT_Y WINDOW_HEIGHT - ANTI_AIRCRAFT_HEIGHT

#define HELICOPTER_WIDTH 225
#define HELICOPTER_HEIGHT 75
#define HELICOPTER_Y 15
#define HELICOPTER_X 15
#define HELICOPTER_VELOCITY 5
